fixes #43
That way could work but forbid usage of fail or any other bash_unit
assertion in the setup_suite function. Otherwise, the shell will just
exit and teardown_suite will not be executed.

diff --git a/bash_unit b/bash_unit
--- a/bash_unit
+++ b/bash_unit
@@ -144,7 +144,26 @@ stacktrace() {
 run_test_suite() {
   local failure=0
 
-  declare -F | "$GREP" ' setup_suite$' >/dev/null && setup_suite
+  if run_setup_suite
+  then
+    run_tests || failure=$?
+  else
+    failure=$?
+  fi
+  run_teardown_suite
+
+  return $failure
+}
+
+run_setup_suite() {
+  if declare -F | "$GREP" ' setup_suite$' >/dev/null
+  then
+    setup_suite
+  fi
+}
+
+run_tests() {
+  local failure=0
 
   for pending_test in $(set | "$GREP"  -E '^(pending|todo).* \(\)' | "$GREP" -E "$test_pattern" | "$SED" -e 's: .*::')
   do
@@ -164,9 +183,6 @@ run_test_suite() {
     )
     failure=$(( $? || failure))
   done
-
-  declare -F | "$GREP" ' teardown_suite$' >/dev/null && teardown_suite
-
   return $failure
 }
 
@@ -174,6 +190,13 @@ run_test() {
   set -e
   notify_test_starting "$__bash_unit_current_test__"
   "$__bash_unit_current_test__" && notify_test_succeeded "$__bash_unit_current_test__"
+}
+
+run_teardown_suite() {
+  if declare -F | "$GREP" ' teardown_suite$' >/dev/null
+  then
+    teardown_suite
+  fi
 }
 
 usage() {
@@ -364,7 +387,7 @@ for test_file in "$@"
 do
   notify_suite_starting "$test_file"
   (
-    set -e # Ensure bash_unit with exit with failure
+    set -e # Ensure bash_unit will exit with failure
            # in case of syntax error.
     if [[ "${STICK_TO_CWD}" != true ]]
     then
